### ISSUE TITLE
Rename & refactor ScoreCard components

### ISSUE THREAD

**Issue by ctsexton** [metro-ontime/frontend#26]
The "ScoreCard", "SimpleScoreCard" and "SimpleScoreCardHeader" components are named and structured poorly. We should have a generic ScoreCard component and then compose more specific ones - something like "AverageWaitTimeScoreCard" and "OnTimeScoreCard" perhaps.

**Comment by paulfox310** [comment]
I will begin working on these cards. For creating the generic ScoreCard I will refer to the common properties and try to make something very flexible. I will keep you updated on my progress.

**Comment by ctsexton** [comment]
Sounds great!

**Comment by dwgillette** [comment]
Jumping on this. Will work at the approach Paul described above.
