### ISSUE TITLE
Get Line filters working

### ISSUE THREAD

**Issue by ctsexton** [metro-ontime/frontend#34]
filter_layout branch:

Currently when you select a new line in filter selector, the React app crashes. This is because the legacy implementation had the app navigate to a new page when each line was selected. We are removing the individual line pages (forcing the routes to index.js with query params set to prepopulate the filters). 

For now, we need to make the filter dropdown correctly select line data from the data object for the appropriate line and supply it to the page.

You will need to inspect the API response to see how it is organized. Lines are named by their ID (801 - 806). 

Another consequence of filtering for line level data is that things like the "comparison" sections of the summary cards will no longer be relevant (and they will cause errors without the right data input). You'll need to find a way to only show those sections when the data is available. You can compose the contents of ScoreCard component to either include or exclude the Comparison component.

**Comment by cuevaskoch** [comment]
Hi, I think this is an interesting project and would love to help out if I can, but I have a conflict on Tuesday nights and can't attend Hack for LA meetings.  Is this still an issue?  It appears to be working fine on https://railstats.org/
