### ISSUE TITLE
Remove history API call from index page

### ISSUE THREAD

**Issue by ctsexton** [metro-ontime/frontend#35]
Related to #34 
We shouldn't need to load the entire history object just to load this page. If we want to display history-based visualizations then the history component should load separately (and async, not server-side).

When the page first loads, the only API endpoint that needs to be resolved is '/network' - this contains enough data to fill out all the non-history-related statistics.

**Comment by bbovenzi** [comment]
`/network` only works for the All Lines filter. Any other line will need its specific data called `line/{lineId}`

@ctsexton Which do you think is a better approach. Combing all basic stats into the `/network` endpoint or calling a new endpoint for every line filter?

**Comment by ctsexton** [comment]
Finally getting onto this! Looking at what happens in the API when we make a request for the "network" data, we can see that it's already using data from the individual line summaries (e.g. to work out the most/least reliable lines at the current point in time). Seeing as we have to load that data anyway, we may as well include it with the payload we send. 

So yes let's just put all data for the current day into the response for the /network endpoint.

As for the history endpoint, we will completely change the model of the response object. Instead of just sending an array of every previous network & line summary, we'll provide historical stats and various arrays of % on-time for a week, 30 days etc. It'll be way easier to load this and display in the frontend.
