### ISSUE TITLE
Fix D3 zoom on Marey diagram

### ISSUE THREAD

**Issue by ctsexton** [metro-ontime/frontend#49]
D3 zooming/panning on scroll/drag fails with the following error:
```
TypeError: Cannot read property 'ctrlKey' of null
```
Looks like there is a solution discussed here: https://github.com/d3/d3-zoom/issues/32

**Comment by Yohandah** [comment]
excuse me for the intrusion ... I have this same exact issue with d3-zoom ... Have you found something to fix it ?
